### ISSUE TITLE
添加集群超时

### ISSUE THREAD

**Issue by yuanjinzhong** [dushixiang/kafka-map#32]
docker 安装

![image](https://user-images.githubusercontent.com/13908993/157231997-99d27445-6671-47e4-bc92-5e9a28b15244.png)
![image](https://user-images.githubusercontent.com/13908993/157232039-7a9a91c8-5983-4460-9290-50ac94b742b1.png)

**Comment by dushixiang** [comment]
> docker 安装
> 
> ![image](https://user-images.githubusercontent.com/13908993/157231997-99d27445-6671-47e4-bc92-5e9a28b15244.png) ![image](https://user-images.githubusercontent.com/13908993/157232039-7a9a91c8-5983-4460-9290-50ac94b742b1.png)

Mac 版 docker 默认无法访问外部网络，详情见 docker 官方文档 https://docs.docker.com/desktop/mac/networking/

**Comment by yuanjinzhong** [comment]
> Mac 版 docker 默认无法访问外部网络

但是我那三个kfaka地址是可以访问的

**Comment by dushixiang** [comment]
> > Mac 版 docker 默认无法访问外部网络
> 
> 但是我那三个kfaka地址是可以访问的

你在容器里面就访问不到了

**Comment by yuanjinzhong** [comment]
> > > Mac 版 docker 默认无法访问外部网络
> > 
> > 
> > 但是我那三个kfaka地址是可以访问的
> 
> 你在容器里面就访问不到了

需要我咋设置呢？docker 这块不是很熟悉

**Comment by dushixiang** [comment]
> > > > Mac 版 docker 默认无法访问外部网络
> > > 
> > > 
> > > 但是我那三个kfaka地址是可以访问的
> > 
> > 
> > 你在容器里面就访问不到了
> 
> 需要我咋设置呢？docker 这块不是很熟悉

换台 Linux 机器安装吧

**Comment by yuanjinzhong** [comment]
> 

可以把kafak-map 和kafka集群 以及zookeeper 写在同一个docker-compose里面吗？这样是不是可以解决网络问题

**Comment by dushixiang** [comment]
> > 
> 
> 可以把kafak-map 和kafka集群 以及zookeeper 写在同一个docker-compose里面吗？这样是不是可以解决网络问题

我觉得应该没有人会把 Mac 当作服务器来使用，因此我只提供了一个简单的安装方式。

**Comment by yuanjinzhong** [comment]
version: '2.1'

services:
  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    restart: always
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
      - ./zk-single-kafka-multiple/zoo1/data:/data
      - ./zk-single-kafka-multiple/zoo1/datalog:/datalog

  kafka1:
    image: confluentinc/cp-kafka:5.4.0
    hostname: kafka1
    restart: always
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    volumes:
      - ./zk-single-kafka-multiple/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zoo1

  kafka2:
    image: confluentinc/cp-kafka:5.4.0
    hostname: kafka2
    restart: always
    container_name: kafka2
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka2:19093,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 2
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    volumes:
      - ./zk-single-kafka-multiple/kafka2/data:/var/lib/kafka/data
    depends_on:
      - zoo1


  kafka3:
    image: confluentinc/cp-kafka:5.4.0
    hostname: kafka3
    restart: always
    container_name: kafka3
    ports:
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka3:19094,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 3
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    volumes:
      - ./zk-single-kafka-multiple/kafka3/data:/var/lib/kafka/data
    depends_on:
      - zoo1

  kafka-manager:  
    image: sheepkiller/kafka-manager:latest
    restart: always
    container_name: kafka-manager
    hostname: kafka-manager
    ports:
      - "9000:9000"
    links:             
      - kafka1
      - kafka2
      - kafka3
    environment:
      ZK_HOSTS: zoo1:2181
      KAFKA_BROKERS: kafka1:9092,kafka2:9093,kafka3:9094
  
  kafka-map:
    image: dushixiang/kafka-map:latest
    restart: always
    container_name: kafka-map
    hostname: kafka-map
    ports:
      - "8080:8080"
    environment:
      DEFAULT_USERNAME: admin
      DEFAULT_PASSWORD: admin
    volumes:
      - ./zk-single-kafka-multiple/kafka-map/data:/usr/local/kafka-map/data       


帮我瞧瞧这个docker-compose 写的有没有问题，是不是缺少什么网络配置。我这样docker-compose.yml up 起来之后，还是没法添加集群。kafka-map的控制台可以访问

**Comment by shuifa** [comment]
我在m1的mac启动这个docker容器。kafka的控制台都无法打开。。

**Comment by shuifa** [comment]
```yaml
version: "3.9"
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    volumes:
      - zookeeper:/data
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: bitnami/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    links:
      - zookeeper
    volumes:
      - kafka:/kafka
    ports:
      - "9092:9092"
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181/kafka"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
  kafka-map:
    image: dushixiang/kafka-map:latest
    container_name: kafka-map
    ports:
      - "8080:8080"
    environment:
      DEFAULT_USERNAME: admin
      DEFAULT_PASSWORD: admin
volumes:
  zookeeper:
  kafka:

```

我这样能用了。。
